// ════════════════════════════════════════════════════════
// PHRASE DATABASE — Japan Start
// ════════════════════════════════════════════════════════
// Two phrase types:
//   1. FIXED — phrase is always the same (greetings, thanks etc)
//   2. TEMPLATE — has a [slot] that gets filled from user's unlocked
//      vocab matching that tag. If nothing unlocked yet, uses fallback.
//
// Each phrase has:
//   id          — unique identifier
//   theme       — category for grouping into blocks
//   english     — English version (with [slot-name] placeholder if template)
//   romaji      — romaji template (with [slot-name] placeholder if template)
//   kana        — kana template (with [slot-name] placeholder if template)
//   slot        — tag name that fills the slot, or null for fixed phrases
//   slotEnglish — what the slot represents in English (used in display)
//   fallback    — { romaji, kana, english } default word for the slot
//   formality   — 'casual' | 'polite' | 'formal'
//   notes       — optional cultural / usage notes
// ════════════════════════════════════════════════════════

window.phraseData = {
  themes: [
    { id: 'greetings',  label: 'Greetings & Goodbyes',     icon: '挨' },
    { id: 'politeness', label: 'Politeness Essentials',    icon: '礼' },
    { id: 'intro',      label: 'Self-Introduction',        icon: '紹' },
    { id: 'restaurant', label: 'At the Restaurant',        icon: '食' },
    { id: 'shopping',   label: 'Shopping',                 icon: '買' },
    { id: 'directions', label: 'Getting Around',           icon: '道' },
    { id: 'hotel',      label: 'Hotel & Accommodation',    icon: '宿' },
    { id: 'help',       label: 'Help & Emergencies',       icon: '助' },
    { id: 'numbers',    label: 'Numbers & Money',          icon: '円' },
    { id: 'smalltalk',  label: 'Small Talk',               icon: '話' },
  ],

  phrases: [
    // ════ GREETINGS & GOODBYES ════
    { id:'g1',  theme:'greetings',  english:'hello / good afternoon',
      romaji:'konnichiwa', kana:'こんにちは',
      slot:null, formality:'polite' },
    { id:'g2',  theme:'greetings',  english:'good morning',
      romaji:'ohayou gozaimasu', kana:'おはようございます',
      slot:null, formality:'polite' },
    { id:'g3',  theme:'greetings',  english:'morning (casual)',
      romaji:'ohayou', kana:'おはよう',
      slot:null, formality:'casual' },
    { id:'g4',  theme:'greetings',  english:'good evening',
      romaji:'konbanwa', kana:'こんばんは',
      slot:null, formality:'polite' },
    { id:'g5',  theme:'greetings',  english:'good night',
      romaji:'oyasuminasai', kana:'おやすみなさい',
      slot:null, formality:'polite' },
    { id:'g6',  theme:'greetings',  english:'goodbye',
      romaji:'sayounara', kana:'さようなら',
      slot:null, formality:'polite',
      notes:'Quite formal — for longer goodbyes' },
    { id:'g7',  theme:'greetings',  english:'see you (casual)',
      romaji:'jaa ne', kana:'じゃあね',
      slot:null, formality:'casual' },
    { id:'g8',  theme:'greetings',  english:'see you tomorrow',
      romaji:'mata ashita', kana:'また あした',
      slot:null, formality:'casual' },
    { id:'g9',  theme:'greetings',  english:"I'm leaving (going out)",
      romaji:'ittekimasu', kana:'いってきます',
      slot:null, formality:'polite',
      notes:'Said by person leaving home' },
    { id:'g10', theme:'greetings',  english:"I'm home",
      romaji:'tadaima', kana:'ただいま',
      slot:null, formality:'casual' },
    { id:'g11', theme:'greetings',  english:'welcome back',
      romaji:'okaerinasai', kana:'おかえりなさい',
      slot:null, formality:'polite',
      notes:'Reply to tadaima' },

    // ════ POLITENESS ESSENTIALS ════
    { id:'p1',  theme:'politeness', english:'thanks',
      romaji:'arigatou', kana:'ありがとう',
      slot:null, formality:'casual' },
    { id:'p2',  theme:'politeness', english:'thank you',
      romaji:'arigatou gozaimasu', kana:'ありがとうございます',
      slot:null, formality:'polite' },
    { id:'p3',  theme:'politeness', english:'thank you very much',
      romaji:'doumo arigatou gozaimasu', kana:'どうも ありがとうございます',
      slot:null, formality:'polite' },
    { id:'p4',  theme:'politeness', english:"you're welcome",
      romaji:'dou itashimashite', kana:'どういたしまして',
      slot:null, formality:'polite' },
    { id:'p5',  theme:'politeness', english:'excuse me / sorry',
      romaji:'sumimasen', kana:'すみません',
      slot:null, formality:'polite',
      notes:'Multi-purpose — gets attention or apologises' },
    { id:'p6',  theme:'politeness', english:"I'm sorry",
      romaji:'gomennasai', kana:'ごめんなさい',
      slot:null, formality:'polite' },
    { id:'p7',  theme:'politeness', english:'sorry (casual)',
      romaji:'gomen', kana:'ごめん',
      slot:null, formality:'casual' },
    { id:'p8',  theme:'politeness', english:'please',
      romaji:'onegaishimasu', kana:'おねがいします',
      slot:null, formality:'polite',
      notes:'Used when requesting' },
    { id:'p9',  theme:'politeness', english:'go ahead / please (offering)',
      romaji:'douzo', kana:'どうぞ',
      slot:null, formality:'polite',
      notes:'Used when offering or inviting' },
    { id:'p10', theme:'politeness', english:'excuse me (entering/leaving)',
      romaji:'shitsurei shimasu', kana:'しつれいします',
      slot:null, formality:'formal' },
    { id:'p11', theme:'politeness', english:'yes',
      romaji:'hai', kana:'はい',
      slot:null, formality:'polite' },
    { id:'p12', theme:'politeness', english:'no',
      romaji:'iie', kana:'いいえ',
      slot:null, formality:'polite' },

    // ════ SELF-INTRODUCTION ════
    { id:'i1', theme:'intro', english:'nice to meet you',
      romaji:'hajimemashite', kana:'はじめまして',
      slot:null, formality:'polite',
      notes:'First-time greeting only' },
    { id:'i2', theme:'intro', english:'pleased to meet you',
      romaji:'yoroshiku onegaishimasu', kana:'よろしく おねがいします',
      slot:null, formality:'polite',
      notes:'Always pairs with introductions' },
    { id:'i3', theme:'intro', english:"I'm from [country]",
      romaji:'[country] kara kimashita', kana:'[country] から きました',
      slot:'country', slotEnglish:'country',
      fallback:{ romaji:'amerika', kana:'アメリカ', english:'America' },
      formality:'polite' },
    { id:'i4', theme:'intro', english:'I understand a little [language]',
      romaji:'[language] ga sukoshi wakarimasu', kana:'[language] が すこし わかります',
      slot:'language', slotEnglish:'language',
      fallback:{ romaji:'nihongo', kana:'にほんご', english:'Japanese' },
      formality:'polite' },
    { id:'i5', theme:'intro', english:'do you speak English?',
      romaji:'eigo ga hanasemasu ka', kana:'えいご が はなせますか',
      slot:null, formality:'polite' },
    { id:'i6', theme:'intro', english:'what is your name?',
      romaji:'onamae wa nan desu ka', kana:'おなまえは なんですか',
      slot:null, formality:'polite' },
    { id:'i7', theme:'intro', english:"I'll have a [drink]",
      romaji:'[drink] o kudasai', kana:'[drink] を ください',
      slot:'drink', slotEnglish:'drink',
      fallback:{ romaji:'mizu', kana:'みず', english:'water' },
      formality:'polite' },

    // ════ AT THE RESTAURANT ════
    { id:'r1', theme:'restaurant', english:'menu, please',
      romaji:'menyuu o kudasai', kana:'メニューを ください',
      slot:null, formality:'polite' },
    { id:'r2', theme:'restaurant', english:'[drink], please',
      romaji:'[drink] o kudasai', kana:'[drink] を ください',
      slot:'drink', slotEnglish:'drink',
      fallback:{ romaji:'mizu', kana:'みず', english:'water' },
      formality:'polite' },
    { id:'r3', theme:'restaurant', english:'I would like [food]',
      romaji:'[food] o onegaishimasu', kana:'[food] を おねがいします',
      slot:'food', slotEnglish:'food',
      fallback:{ romaji:'sushi', kana:'すし', english:'sushi' },
      formality:'polite' },
    { id:'r4', theme:'restaurant', english:'this one, please',
      romaji:'kore o kudasai', kana:'これを ください',
      slot:null, formality:'polite',
      notes:'Point at menu' },
    { id:'r5', theme:'restaurant', english:'what do you recommend?',
      romaji:'osusume wa nan desu ka', kana:'おすすめは なんですか',
      slot:null, formality:'polite' },
    { id:'r6', theme:'restaurant', english:"it's delicious",
      romaji:'oishii desu', kana:'おいしい です',
      slot:null, formality:'polite' },
    { id:'r7', theme:'restaurant', english:'the bill, please',
      romaji:'okaikei onegaishimasu', kana:'おかいけい おねがいします',
      slot:null, formality:'polite' },
    { id:'r8', theme:'restaurant', english:'(said before eating)',
      romaji:'itadakimasu', kana:'いただきます',
      slot:null, formality:'polite',
      notes:'Cultural ritual before eating' },
    { id:'r9', theme:'restaurant', english:'(said after eating)',
      romaji:'gochisousama deshita', kana:'ごちそうさまでした',
      slot:null, formality:'polite',
      notes:'Cultural ritual after eating' },
    { id:'r10',theme:'restaurant', english:'I am vegetarian',
      romaji:'bejitarian desu', kana:'ベジタリアン です',
      slot:null, formality:'polite' },
    { id:'r11',theme:'restaurant', english:'do you have [food]?',
      romaji:'[food] wa arimasu ka', kana:'[food] は ありますか',
      slot:'food', slotEnglish:'food',
      fallback:{ romaji:'sushi', kana:'すし', english:'sushi' },
      formality:'polite' },

    // ════ SHOPPING ════
    { id:'s1', theme:'shopping', english:'how much is it?',
      romaji:'ikura desu ka', kana:'いくら ですか',
      slot:null, formality:'polite' },
    { id:'s2', theme:'shopping', english:'how much is this?',
      romaji:'kore wa ikura desu ka', kana:'これは いくら ですか',
      slot:null, formality:'polite' },
    { id:'s3', theme:'shopping', english:"it's expensive",
      romaji:'takai desu', kana:'たかい です',
      slot:null, formality:'polite' },
    { id:'s4', theme:'shopping', english:"it's cheap",
      romaji:'yasui desu', kana:'やすい です',
      slot:null, formality:'polite' },
    { id:'s5', theme:'shopping', english:"I'll take this",
      romaji:'kore o kudasai', kana:'これを ください',
      slot:null, formality:'polite' },
    { id:'s6', theme:'shopping', english:'can I use a credit card?',
      romaji:'kurejitto kaado wa tsukaemasu ka', kana:'クレジットカードは つかえますか',
      slot:null, formality:'polite' },
    { id:'s7', theme:'shopping', english:"I don't need a bag",
      romaji:'fukuro wa irimasen', kana:'ふくろは いりません',
      slot:null, formality:'polite' },
    { id:'s8', theme:'shopping', english:'just looking',
      romaji:'miteiru dake desu', kana:'みているだけです',
      slot:null, formality:'polite' },
    { id:'s9', theme:'shopping', english:'do you have it in [colour]?',
      romaji:'[colour] no wa arimasu ka', kana:'[colour] のは ありますか',
      slot:'colour', slotEnglish:'colour',
      fallback:{ romaji:'aka', kana:'あか', english:'red' },
      formality:'polite' },
    { id:'s10',theme:'shopping', english:'I want to buy [object]',
      romaji:'[object] o kaitai desu', kana:'[object] を かいたい です',
      slot:'object', slotEnglish:'object',
      fallback:{ romaji:'hon', kana:'ほん', english:'book' },
      formality:'polite' },

    // ════ GETTING AROUND ════
    { id:'d1', theme:'directions', english:'where is the [place]?',
      romaji:'[place] wa doko desu ka', kana:'[place] は どこ ですか',
      slot:'place', slotEnglish:'place',
      fallback:{ romaji:'eki', kana:'えき', english:'station' },
      formality:'polite' },
    { id:'d2', theme:'directions', english:'where is the toilet?',
      romaji:'toire wa doko desu ka', kana:'トイレは どこ ですか',
      slot:null, formality:'polite' },
    { id:'d3', theme:'directions', english:"it's on the right",
      romaji:'migi desu', kana:'みぎ です',
      slot:null, formality:'polite' },
    { id:'d4', theme:'directions', english:"it's on the left",
      romaji:'hidari desu', kana:'ひだり です',
      slot:null, formality:'polite' },
    { id:'d5', theme:'directions', english:'straight ahead',
      romaji:'massugu desu', kana:'まっすぐ です',
      slot:null, formality:'polite' },
    { id:'d6', theme:'directions', english:'is it nearby?',
      romaji:'chikaku desu ka', kana:'ちかく ですか',
      slot:null, formality:'polite' },
    { id:'d7', theme:'directions', english:'how long does it take?',
      romaji:'donokurai kakarimasu ka', kana:'どのくらい かかりますか',
      slot:null, formality:'polite' },
    { id:'d8', theme:'directions', english:"I'll take a [transport]",
      romaji:'[transport] ni norimasu', kana:'[transport] に のります',
      slot:'transport', slotEnglish:'transport',
      fallback:{ romaji:'densha', kana:'でんしゃ', english:'train' },
      formality:'polite' },
    { id:'d9', theme:'directions', english:'please show me the map',
      romaji:'chizu o misete kudasai', kana:'ちずを みせて ください',
      slot:null, formality:'polite' },
    { id:'d10',theme:'directions', english:'I want to go to the [place]',
      romaji:'[place] ni ikitai desu', kana:'[place] に いきたい です',
      slot:'place', slotEnglish:'place',
      fallback:{ romaji:'eki', kana:'えき', english:'station' },
      formality:'polite' },

    // ════ HOTEL & ACCOMMODATION ════
    { id:'h1', theme:'hotel', english:'I have a reservation',
      romaji:'yoyaku ga arimasu', kana:'よやくが あります',
      slot:null, formality:'polite' },
    { id:'h2', theme:'hotel', english:'check-in, please',
      romaji:'chekkuin onegaishimasu', kana:'チェックイン おねがいします',
      slot:null, formality:'polite' },
    { id:'h3', theme:'hotel', english:'check-out, please',
      romaji:'chekku auto onegaishimasu', kana:'チェックアウト おねがいします',
      slot:null, formality:'polite' },
    { id:'h4', theme:'hotel', english:"it's the room key",
      romaji:'heya no kagi desu', kana:'へやの かぎです',
      slot:null, formality:'polite' },
    { id:'h5', theme:'hotel', english:"what's the wi-fi password?",
      romaji:'wai-fai no pasuwaado wa', kana:'Wi-Fiの パスワードは',
      slot:null, formality:'polite' },
    { id:'h6', theme:'hotel', english:'what time is breakfast?',
      romaji:'asagohan wa nanji desu ka', kana:'あさごはんは なんじ ですか',
      slot:null, formality:'polite' },
    { id:'h7', theme:'hotel', english:'I want to stay one more night',
      romaji:'mou ippaku shitai desu', kana:'もう いっぱく したい です',
      slot:null, formality:'polite' },
    { id:'h8', theme:'hotel', english:'where is the [room]?',
      romaji:'[room] wa doko desu ka', kana:'[room] は どこ ですか',
      slot:'room', slotEnglish:'room',
      fallback:{ romaji:'ofuro', kana:'おふろ', english:'bath' },
      formality:'polite' },

    // ════ HELP & EMERGENCIES ════
    { id:'e1', theme:'help', english:'please help me',
      romaji:'tasukete kudasai', kana:'たすけて ください',
      slot:null, formality:'polite' },
    { id:'e2', theme:'help', english:'help!',
      romaji:'tasukete', kana:'たすけて',
      slot:null, formality:'casual',
      notes:'Urgent' },
    { id:'e3', theme:'help', english:'I am sick',
      romaji:'byouki desu', kana:'びょうき です',
      slot:null, formality:'polite' },
    { id:'e4', theme:'help', english:'my [body-part] hurts',
      romaji:'[body-part] ga itai desu', kana:'[body-part] が いたい です',
      slot:'body-part', slotEnglish:'body part',
      fallback:{ romaji:'atama', kana:'あたま', english:'head' },
      formality:'polite' },
    { id:'e5', theme:'help', english:'please call a doctor',
      romaji:'isha o yonde kudasai', kana:'いしゃを よんで ください',
      slot:null, formality:'polite' },
    { id:'e6', theme:'help', english:'please call the police',
      romaji:'keisatsu o yonde kudasai', kana:'けいさつを よんで ください',
      slot:null, formality:'polite' },
    { id:'e7', theme:'help', english:'please call an ambulance',
      romaji:'kyuukyuusha o yonde kudasai', kana:'きゅうきゅうしゃを よんで ください',
      slot:null, formality:'polite' },
    { id:'e8', theme:'help', english:'I lost my luggage',
      romaji:'nimotsu o nakushimashita', kana:'にもつを なくしました',
      slot:null, formality:'polite' },
    { id:'e9', theme:'help', english:"I'm lost",
      romaji:'michi ni mayoimashita', kana:'みちに まよいました',
      slot:null, formality:'polite' },
    { id:'e10',theme:'help', english:'are you okay?',
      romaji:'daijoubu desu ka', kana:'だいじょうぶ ですか',
      slot:null, formality:'polite' },
    { id:'e11',theme:'help', english:"I'm okay",
      romaji:'daijoubu desu', kana:'だいじょうぶ です',
      slot:null, formality:'polite' },

    // ════ NUMBERS & MONEY ════
    { id:'n1', theme:'numbers', english:"it's 100 yen",
      romaji:'hyaku-en desu', kana:'ひゃくえん です',
      slot:null, formality:'polite' },
    { id:'n2', theme:'numbers', english:"it's 1,000 yen",
      romaji:'sen-en desu', kana:'せんえん です',
      slot:null, formality:'polite' },
    { id:'n3', theme:'numbers', english:"I'll pay in cash",
      romaji:'genkin de haraimasu', kana:'げんきんで はらいます',
      slot:null, formality:'polite' },
    { id:'n4', theme:'numbers', english:'can I pay by card?',
      romaji:'kaado de haraemasu ka', kana:'カードで はらえますか',
      slot:null, formality:'polite' },
    { id:'n5', theme:'numbers', english:'how much in total?',
      romaji:'zenbu de ikura desu ka', kana:'ぜんぶで いくら ですか',
      slot:null, formality:'polite' },
    { id:'n6', theme:'numbers', english:'two please',
      romaji:'futatsu kudasai', kana:'ふたつ ください',
      slot:null, formality:'polite',
      notes:'Counter for objects' },
    { id:'n7', theme:'numbers', english:'one please',
      romaji:'hitotsu kudasai', kana:'ひとつ ください',
      slot:null, formality:'polite' },
    { id:'n8', theme:'numbers', english:'receipt, please',
      romaji:'reshiito o kudasai', kana:'レシートを ください',
      slot:null, formality:'polite' },
    { id:'n9', theme:'numbers', english:'[number] please',
      romaji:'[number-word] kudasai', kana:'[number-word] ください',
      slot:'number-word', slotEnglish:'number',
      fallback:{ romaji:'hitotsu', kana:'ひとつ', english:'one' },
      formality:'polite' },

    // ════ SMALL TALK ════
    { id:'t1', theme:'smalltalk', english:'how are you?',
      romaji:'genki desu ka', kana:'げんき ですか',
      slot:null, formality:'polite' },
    { id:'t2', theme:'smalltalk', english:"I'm good",
      romaji:'genki desu', kana:'げんき です',
      slot:null, formality:'polite' },
    { id:'t3', theme:'smalltalk', english:"nice weather, isn't it?",
      romaji:'ii tenki desu ne', kana:'いい てんき ですね',
      slot:null, formality:'polite' },
    { id:'t4', theme:'smalltalk', english:"it's [weather]",
      romaji:'[weather] desu', kana:'[weather] です',
      slot:'weather', slotEnglish:'weather',
      fallback:{ romaji:'ame', kana:'あめ', english:'rain' },
      formality:'polite' },
    { id:'t5', theme:'smalltalk', english:"it's cold",
      romaji:'samui desu', kana:'さむい です',
      slot:null, formality:'polite' },
    { id:'t6', theme:'smalltalk', english:"it's hot",
      romaji:'atsui desu', kana:'あつい です',
      slot:null, formality:'polite' },
    { id:'t7', theme:'smalltalk', english:'Japan is wonderful',
      romaji:'nihon wa subarashii desu', kana:'にほんは すばらしい です',
      slot:null, formality:'polite' },
    { id:'t8', theme:'smalltalk', english:"it's interesting",
      romaji:'omoshiroi desu', kana:'おもしろい です',
      slot:null, formality:'polite' },
    { id:'t9', theme:'smalltalk', english:"it's fun",
      romaji:'tanoshii desu', kana:'たのしい です',
      slot:null, formality:'polite' },
    { id:'t10',theme:'smalltalk', english:"I'm tired",
      romaji:'tsukaremashita', kana:'つかれました',
      slot:null, formality:'polite' },
    { id:'t11',theme:'smalltalk', english:"I'm hungry",
      romaji:'onaka ga sukimashita', kana:'おなかが すきました',
      slot:null, formality:'polite' },
    { id:'t12',theme:'smalltalk', english:'I like [food]',
      romaji:'[food] ga suki desu', kana:'[food] が すき です',
      slot:'food', slotEnglish:'food',
      fallback:{ romaji:'sushi', kana:'すし', english:'sushi' },
      formality:'polite' },
    { id:'t13',theme:'smalltalk', english:'my favourite colour is [colour]',
      romaji:'sukina iro wa [colour] desu', kana:'すきな いろは [colour] です',
      slot:'colour', slotEnglish:'colour',
      fallback:{ romaji:'ao', kana:'あお', english:'blue' },
      formality:'polite' },
  ],
};
