// ════════════════════════════════════════════════════════
// PHRASE DATABASE — Japan Start
// ════════════════════════════════════════════════════════
// Fields:
//   id            — unique identifier
//   theme         — category
//   scenario      — real-world situation prompt (used as quiz question)
//   english       — English translation (shown after correct answer)
//   romaji        — romaji (with [slot] placeholder if template)
//   kana          — kana (with [slot] placeholder if template)
//   slot          — vocab tag to fill slot, or null
//   slotScenario  — how to describe the slot in the scenario (e.g. "a place")
//   fallback      — default slot word { romaji, kana, english }
//   formality     — casual | polite | formal
//   notes         — cultural/usage notes
//   mcWrong       — 3 wrong MC answers for Type 2 questions (romaji)
// ════════════════════════════════════════════════════════

window.phraseData = {
  themes: [
    { id:'greetings',  label:'Greetings & Goodbyes',    icon:'挨' },
    { id:'politeness', label:'Politeness Essentials',   icon:'礼' },
    { id:'intro',      label:'Self-Introduction',       icon:'紹' },
    { id:'restaurant', label:'At the Restaurant',       icon:'食' },
    { id:'shopping',   label:'Shopping',                icon:'買' },
    { id:'directions', label:'Getting Around',          icon:'道' },
    { id:'hotel',      label:'Hotel & Accommodation',   icon:'宿' },
    { id:'help',       label:'Help & Emergencies',      icon:'助' },
    { id:'numbers',    label:'Numbers & Money',         icon:'円' },
    { id:'smalltalk',  label:'Small Talk',              icon:'話' },
  ],

  phrases: [

    // ══ GREETINGS & GOODBYES ══════════════════════════════
    { id:'g1', theme:'greetings',
      scenario: "You pass someone in the street during the afternoon",
      english: "hello / good afternoon",
      romaji: 'konnichiwa', kana: 'こんにちは',
      slot:null, formality:'polite',
      haWaNote: true,
      mcWrong: ['konbanwa','ohayou','sayounara'] },

    { id:'g2', theme:'greetings',
      scenario: "You arrive at your hotel early in the morning and greet the staff",
      english: "good morning",
      romaji: 'ohayou gozaimasu', kana: 'おはようございます',
      slot:null, formality:'polite',
      mcWrong: ['konnichiwa','oyasuminasai','konbanwa'] },

    { id:'g3', theme:'greetings',
      scenario: "You bump into a friend before 10am",
      english: "morning (casual)",
      romaji: 'ohayou', kana: 'おはよう',
      slot:null, formality:'casual',
      mcWrong: ['konnichiwa','jaa ne','tadaima'] },

    { id:'g4', theme:'greetings',
      scenario: "You meet your host family after sunset",
      english: "good evening",
      romaji: 'konbanwa', kana: 'こんばんは',
      slot:null, formality:'polite',
      haWaNote: true,
      mcWrong: ['konnichiwa','ohayou gozaimasu','ittekimasu'] },

    { id:'g5', theme:'greetings',
      scenario: "You're heading to bed and want to say goodnight",
      english: "good night",
      romaji: 'oyasuminasai', kana: 'おやすみなさい',
      slot:null, formality:'polite',
      mcWrong: ['sayounara','konbanwa','tadaima'] },

    { id:'g6', theme:'greetings',
      scenario: "You're leaving a place and won't be back for a long time",
      english: "goodbye",
      romaji: 'sayounara', kana: 'さようなら',
      slot:null, formality:'polite',
      notes: 'More final than jaa ne — for longer or permanent goodbyes',
      mcWrong: ['jaa ne','oyasuminasai','ittekimasu'] },

    { id:'g7', theme:'greetings',
      scenario: "You're leaving a friend's house after hanging out",
      english: "see you (casual)",
      romaji: 'jaa ne', kana: 'じゃあね',
      slot:null, formality:'casual',
      mcWrong: ['sayounara','ohayou','mata ashita'] },

    { id:'g8', theme:'greetings',
      scenario: "You're saying goodbye to someone you'll see the next day",
      english: "see you tomorrow",
      romaji: 'mata ashita', kana: 'また|あした',
      slot:null, formality:'casual',
      mcWrong: ['jaa ne','sayounara','tadaima'] },

    { id:'g9', theme:'greetings',
      scenario: "You're leaving your host family's house for the day",
      english: "I'm heading out",
      romaji: 'itte kimasu', kana: 'いって|きます',
      slot:null, formality:'polite',
      notes: 'Said by the person leaving — family replies itterasshai',
      mcWrong: ['tadaima','okaerinasai','sayounara'] },

    { id:'g10', theme:'greetings',
      scenario: "You arrive back at your accommodation after a day out",
      english: "I'm home",
      romaji: 'tadaima', kana: 'ただいま',
      slot:null, formality:'casual',
      mcWrong: ['ittekimasu','okaerinasai','konnichiwa'] },

    { id:'g11', theme:'greetings',
      scenario: "Your host returns home and you want to welcome them back",
      english: "welcome back",
      romaji: 'okaerinasai', kana: 'おかえり|なさい',
      slot:null, formality:'polite',
      notes: 'The reply when someone says tadaima',
      mcWrong: ['tadaima','ittekimasu','konnichiwa'] },

    // ══ POLITENESS ESSENTIALS ═════════════════════════════
    { id:'p1', theme:'politeness',
      scenario: "A friend does something nice for you",
      english: "thanks",
      romaji: 'arigatou', kana: 'ありがとう',
      slot:null, formality:'casual',
      mcWrong: ['sumimasen','douzo','gomennasai'] },

    { id:'p2', theme:'politeness',
      scenario: "A shop assistant helps you find what you're looking for",
      english: "thank you",
      romaji: 'arigatou gozaimasu', kana: 'ありがとう|ございます',
      slot:null, formality:'polite',
      mcWrong: ['sumimasen','dou itashimashite','onegaishimasu'] },

    { id:'p3', theme:'politeness',
      scenario: "Someone goes out of their way to help you with directions",
      english: "thank you very much",
      romaji: 'doumo arigatou gozaimasu', kana: 'どうも|ありがとう|ございます',
      slot:null, formality:'polite',
      mcWrong: ['arigatou gozaimasu','sumimasen','shitsurei shimasu'] },

    { id:'p4', theme:'politeness',
      scenario: "Someone thanks you and you want to say no problem",
      english: "you're welcome",
      romaji: 'dou itashimashite', kana: 'どう|いたしまして',
      slot:null, formality:'polite',
      mcWrong: ['arigatou','douzo','onegaishimasu'] },

    { id:'p5', theme:'politeness',
      scenario: "You want to get a busy waiter's attention",
      english: "excuse me",
      romaji: 'sumimasen', kana: 'すみません',
      slot:null, formality:'polite',
      notes: 'Also works as a light apology — very versatile',
      mcWrong: ['gomennasai','arigatou gozaimasu','shitsurei shimasu'] },

    { id:'p6', theme:'politeness',
      scenario: "You accidentally bump into someone and want to properly apologise",
      english: "I'm sorry",
      romaji: 'gomennasai', kana: 'ごめん|なさい',
      slot:null, formality:'polite',
      mcWrong: ['sumimasen','shitsurei shimasu','arigatou'] },

    { id:'p7', theme:'politeness',
      scenario: "You're late to meet a friend and give a quick casual apology",
      english: "sorry (casual)",
      romaji: 'gomen', kana: 'ごめん',
      slot:null, formality:'casual',
      mcWrong: ['gomennasai','sumimasen','arigatou'] },

    { id:'p8', theme:'politeness',
      scenario: "You ask the receptionist if she can call you a taxi",
      english: "please (requesting something)",
      romaji: 'onegaishimasu', kana: 'おねがい|します',
      slot:null, formality:'polite',
      notes: 'Said after making a request — makes it polite',
      mcWrong: ['douzo','sumimasen','arigatou gozaimasu'] },

    { id:'p9', theme:'politeness',
      scenario: "You hold a door open and gesture for someone to go through first",
      english: "please go ahead / after you",
      romaji: 'douzo', kana: 'どうぞ',
      slot:null, formality:'polite',
      notes: 'Also used when offering something — go ahead, here you are',
      mcWrong: ['onegaishimasu','sumimasen','dou itashimashite'] },

    { id:'p10', theme:'politeness',
      scenario: "You need to walk through a group of people in a corridor",
      english: "excuse me (passing through)",
      romaji: 'shitsurei shimasu', kana: 'しつれい|します',
      slot:null, formality:'formal',
      notes: 'Also said when entering or leaving a formal room',
      mcWrong: ['sumimasen','gomennasai','douzo'] },

    { id:'p11', theme:'politeness',
      scenario: "The staff asks if you want a bag and you do",
      english: "yes",
      romaji: 'hai', kana: 'はい',
      slot:null, formality:'polite',
      mcWrong: ['iie','douzo','onegaishimasu'] },

    { id:'p12', theme:'politeness',
      scenario: "The staff asks if you want a bag and you don't",
      english: "no",
      romaji: 'iie', kana: 'いいえ',
      slot:null, formality:'polite',
      mcWrong: ['hai','gomen','sumimasen'] },

    // ══ SELF-INTRODUCTION ══════════════════════════════════
    { id:'i1', theme:'intro',
      scenario: "You meet your Japanese homestay family for the first time",
      english: "nice to meet you",
      romaji: 'hajimemashite', kana: 'はじめ|まして',
      slot:null, formality:'polite',
      notes: 'Only used the very first time you meet someone',
      mcWrong: ['konnichiwa','yoroshiku onegaishimasu','arigatou gozaimasu'] },

    { id:'i2', theme:'intro',
      scenario: "After introducing yourself, you close the introduction politely",
      english: "pleased to meet you / I look forward to it",
      romaji: 'yoroshiku onegaishimasu', kana: 'よろしく|おねがい|します',
      slot:null, formality:'polite',
      notes: 'Always paired with hajimemashite — a set phrase ending',
      mcWrong: ['hajimemashite','arigatou gozaimasu','dou itashimashite'] },

    { id:'i3', theme:'intro',
      scenario: "Someone asks where you're from — you tell them your country",
      english: "I'm from [country]",
      romaji: '[country] kara kimashita', kana: '[country]|から|きました',
      slot:'country', slotScenario:'a country',
      fallback:{ romaji:'oosutoraria', kana:'オーストラリア', english:'Australia' },
      formality:'polite',
      mcWrong: ['nihon ni ikimashita','[country] desu','[country] ga suki desu'] },

    { id:'i4', theme:'intro',
      scenario: "You want to explain that you only know a little Japanese",
      english: "I understand a little Japanese",
      romaji: 'nihongo ga sukoshi wakarimasu', kana: 'にほんごが|すこし|わかります',
      slot:null, formality:'polite',
      mcWrong: ['nihongo ga jouzu desu','nihongo ga wakarimasen','sukoshi hanasemasu'] },

    { id:'i5', theme:'intro',
      scenario: "You're struggling and want to ask if they speak English",
      english: "do you speak English?",
      romaji: 'eigo ga hanasemasu ka', kana: 'えいごが|はなせますか',
      slot:null, formality:'polite',
      mcWrong: ['nihongo ga wakarimasu ka','eigo o kudasai','eigo desu ka'] },

    { id:'i6', theme:'intro',
      scenario: "You want to ask someone their name",
      english: "what is your name?",
      romaji: 'onamae wa nan desu ka', kana: 'おなまえは|なんですか',
      slot:null, formality:'polite',
      mcWrong: ['doko kara kimashita ka','ikutsu desu ka','nani o shimasu ka'] },

    { id:'i7', theme:'intro',
      scenario: "You've just arrived and want to let them know your name",
      english: "I am [name]",
      romaji: 'watashi wa [name] desu', kana: 'わたしは|[name]|です',
      slot:null, formality:'polite',
      notes: 'Replace [name] with your own name',
      mcWrong: ['watashi ga suki desu','[name] kara kimashita','[name] o kudasai'] },

    // ══ AT THE RESTAURANT ═════════════════════════════════
    { id:'r1', theme:'restaurant',
      scenario: "You sit down and the waiter comes over — you need to see the menu",
      english: "menu, please",
      romaji: 'menyuu o kudasai', kana: 'メニューを|ください',
      slot:null, formality:'polite',
      mcWrong: ['okaikei onegaishimasu','mizu o kudasai','osusume wa nan desu ka'] },

    { id:'r2', theme:'restaurant',
      scenario: "You're thirsty and want to order a drink",
      english: "a [drink], please",
      romaji: '[drink] o kudasai', kana: '[drink]を|ください',
      slot:'drink', slotScenario:'a drink',
      fallback:{ romaji:'mizu', kana:'みず', english:'water' },
      formality:'polite',
      mcWrong: ['[drink] ga arimasu ka','[drink] wa doko desu ka','[drink] o tabemasu'] },

    { id:'r3', theme:'restaurant',
      scenario: "You've decided what you want to eat and are ordering",
      english: "I would like [food], please",
      romaji: '[food] o onegaishimasu', kana: '[food]を|おねがい|します',
      slot:'food', slotScenario:'a food item',
      fallback:{ romaji:'sushi', kana:'すし', english:'sushi' },
      formality:'polite',
      mcWrong: ['[food] ga oishii desu','[food] wa arimasu ka','[food] o kuremasu ka'] },

    { id:'r4', theme:'restaurant',
      scenario: "You can't read the menu but you see someone else's food and want that",
      english: "this one, please",
      romaji: 'kore o kudasai', kana: 'これを|ください',
      slot:null, formality:'polite',
      notes: 'Point at what you want — very useful',
      mcWrong: ['are o kudasai','sore wa nan desu ka','kore ga oishii desu'] },

    { id:'r5', theme:'restaurant',
      scenario: "You're not sure what to order and want the waiter's suggestion",
      english: "what do you recommend?",
      romaji: 'osusume wa nan desu ka', kana: 'おすすめは|なんですか',
      slot:null, formality:'polite',
      mcWrong: ['menyuu o kudasai','oishii desu ne','kore wa nan desu ka'] },

    { id:'r6', theme:'restaurant',
      scenario: "You've just taken a bite and it's fantastic",
      english: "it's delicious!",
      romaji: 'oishii desu', kana: 'おいしい|です',
      slot:null, formality:'polite',
      mcWrong: ['oishikatta desu','mazui desu','sugoi desu'] },

    { id:'r7', theme:'restaurant',
      scenario: "You've finished your meal and want to pay",
      english: "the bill, please",
      romaji: 'okaikei onegaishimasu', kana: 'おかいけい|おねがい|します',
      slot:null, formality:'polite',
      mcWrong: ['menyuu o kudasai','arigatou gozaimasu','mizu o kudasai'] },

    { id:'r8', theme:'restaurant',
      scenario: "Your food arrives and everyone is about to eat",
      english: "let's eat (said before eating)",
      romaji: 'itadakimasu', kana: 'いただきます',
      slot:null, formality:'polite',
      notes: 'Cultural ritual — always said before eating',
      mcWrong: ['gochisousama deshita','douzo','arigatou gozaimasu'] },

    { id:'r9', theme:'restaurant',
      scenario: "You've finished your meal and want to express gratitude for it",
      english: "thank you for the meal (said after eating)",
      romaji: 'gochisousama deshita', kana: 'ごちそうさま|でした',
      slot:null, formality:'polite',
      notes: 'Cultural ritual — always said after eating',
      mcWrong: ['itadakimasu','arigatou gozaimasu','oishii desu'] },

    { id:'r10', theme:'restaurant',
      scenario: "You need to tell the restaurant you don't eat meat",
      english: "I am vegetarian",
      romaji: 'bejitarian desu', kana: 'ベジタリアン|です',
      slot:null, formality:'polite',
      mcWrong: ['niku ga suki desu','niku o kudasai','niku ga arimasu ka'] },

    { id:'r11', theme:'restaurant',
      scenario: "You want to check if a specific dish is available",
      english: "do you have [food]?",
      romaji: '[food] wa arimasu ka', kana: '[food]は|ありますか',
      slot:'food', slotScenario:'a food item',
      fallback:{ romaji:'sushi', kana:'すし', english:'sushi' },
      formality:'polite',
      mcWrong: ['[food] o kudasai','[food] wa doko desu ka','[food] ga oishii desu'] },

    // ══ SHOPPING ══════════════════════════════════════════
    { id:'s1', theme:'shopping',
      scenario: "You pick something up in a shop and want to know the price",
      english: "how much is it?",
      romaji: 'ikura desu ka', kana: 'いくら|ですか',
      slot:null, formality:'polite',
      mcWrong: ['kore o kudasai','yasui desu ne','ikutsu desu ka'] },

    { id:'s2', theme:'shopping',
      scenario: "You're holding a specific item and asking its price",
      english: "how much is this?",
      romaji: 'kore wa ikura desu ka', kana: 'これは|いくら|ですか',
      slot:null, formality:'polite',
      mcWrong: ['ikura desu ka','sore wa nan desu ka','kore o kudasai'] },

    { id:'s3', theme:'shopping',
      scenario: "You see the price tag and think it's too much",
      english: "it's expensive",
      romaji: 'takai desu', kana: 'たかい|です',
      slot:null, formality:'polite',
      mcWrong: ['yasui desu','chotto takai desu','ikura desu ka'] },

    { id:'s4', theme:'shopping',
      scenario: "You find a real bargain and want to comment on the price",
      english: "it's cheap!",
      romaji: 'yasui desu', kana: 'やすい|です',
      slot:null, formality:'polite',
      mcWrong: ['takai desu','ikura desu ka','oishii desu'] },

    { id:'s5', theme:'shopping',
      scenario: "You've decided to buy what you're holding",
      english: "I'll take this",
      romaji: 'kore o kudasai', kana: 'これを|ください',
      slot:null, formality:'polite',
      mcWrong: ['kore wa ikura desu ka','sore o misete kudasai','kore ga suki desu'] },

    { id:'s6', theme:'shopping',
      scenario: "You don't have cash and want to pay by card",
      english: "can I use a credit card?",
      romaji: 'kurejitto kaado wa tsukaemasu ka', kana: 'クレジットカードは|つかえますか',
      slot:null, formality:'polite',
      mcWrong: ['genkin de haraimasu','kaado o kudasai','ikura desu ka'] },

    { id:'s7', theme:'shopping',
      scenario: "The cashier asks if you want a plastic bag — you don't need one",
      english: "I don't need a bag",
      romaji: 'fukuro wa irimasen', kana: 'ふくろは|いりません',
      slot:null, formality:'polite',
      mcWrong: ['fukuro o kudasai','irimasen','yasui desu'] },

    { id:'s8', theme:'shopping',
      scenario: "A shop assistant approaches and asks if you need help",
      english: "just looking, thanks",
      romaji: 'miteiru dake desu', kana: 'みている|だけ|です',
      slot:null, formality:'polite',
      mcWrong: ['kore o kudasai','sumimasen','ikura desu ka'] },

    { id:'s9', theme:'shopping',
      scenario: "You like an item but want to know if it comes in a different colour",
      english: "do you have it in [colour]?",
      romaji: '[colour] no wa arimasu ka', kana: '[colour]のは|ありますか',
      slot:'colour', slotScenario:'a colour',
      fallback:{ romaji:'aka', kana:'あか', english:'red' },
      formality:'polite',
      mcWrong: ['[colour] ga suki desu','[colour] desu ka','[colour] o kudasai'] },

    { id:'s10', theme:'shopping',
      scenario: "You decide you want to purchase a specific item",
      english: "I want to buy [object]",
      romaji: '[object] o kaitai desu', kana: '[object]を|かいたい|です',
      slot:'object', slotScenario:'an item',
      fallback:{ romaji:'hon', kana:'ほん', english:'a book' },
      formality:'polite',
      mcWrong: ['[object] o kudasai','[object] ga hoshii desu','[object] wa ikura desu ka'] },

    // ══ GETTING AROUND ════════════════════════════════════
    { id:'d1', theme:'directions',
      scenario: "You're lost and need to ask where a place is",
      english: "where is the [place]?",
      romaji: '[place] wa doko desu ka', kana: '[place]は|どこ|ですか',
      slot:'place', slotScenario:'a destination',
      fallback:{ romaji:'eki', kana:'えき', english:'station' },
      formality:'polite',
      mcWrong: ['[place] ni ikimasu','[place] wa dou desu ka','[place] o misete kudasai'] },

    { id:'d2', theme:'directions',
      scenario: "You urgently need to find the nearest toilet",
      english: "where is the toilet?",
      romaji: 'toire wa doko desu ka', kana: 'トイレは|どこ|ですか',
      slot:null, formality:'polite',
      mcWrong: ['eki wa doko desu ka','toire o kudasai','chikaku desu ka'] },

    { id:'d3', theme:'directions',
      scenario: "Someone asks for directions — you tell them to turn right",
      english: "it's on the right",
      romaji: 'migi desu', kana: 'みぎ|です',
      slot:null, formality:'polite',
      mcWrong: ['hidari desu','massugu desu','chikaku desu'] },

    { id:'d4', theme:'directions',
      scenario: "Someone asks for directions — you tell them to turn left",
      english: "it's on the left",
      romaji: 'hidari desu', kana: 'ひだり|です',
      slot:null, formality:'polite',
      mcWrong: ['migi desu','massugu desu','mukou desu'] },

    { id:'d5', theme:'directions',
      scenario: "You're giving directions and the place is straight ahead",
      english: "straight ahead",
      romaji: 'massugu desu', kana: 'まっすぐ|です',
      slot:null, formality:'polite',
      mcWrong: ['migi desu','hidari desu','chikaku desu'] },

    { id:'d6', theme:'directions',
      scenario: "Someone gives you directions and you want to confirm it's close",
      english: "is it nearby?",
      romaji: 'chikaku desu ka', kana: 'ちかく|ですか',
      slot:null, formality:'polite',
      mcWrong: ['tooi desu ka','massugu desu ka','dono kurai desu ka'] },

    { id:'d7', theme:'directions',
      scenario: "You want to know how long it'll take to get somewhere",
      english: "how long does it take?",
      romaji: 'donokurai kakarimasu ka', kana: 'どのくらい|かかりますか',
      slot:null, formality:'polite',
      mcWrong: ['ikura desu ka','doko desu ka','nani desu ka'] },

    { id:'d8', theme:'directions',
      scenario: "You decide to take a specific type of transport to get there",
      english: "I'll take the [transport]",
      romaji: '[transport] ni norimasu', kana: '[transport]に|のります',
      slot:'transport', slotScenario:'a type of transport',
      fallback:{ romaji:'densha', kana:'でんしゃ', english:'train' },
      formality:'polite',
      mcWrong: ['[transport] ni ikimasu','[transport] wa doko desu ka','[transport] o kudasai'] },

    { id:'d9', theme:'directions',
      scenario: "You're completely lost and ask someone to show you on a map",
      english: "please show me on the map",
      romaji: 'chizu o misete kudasai', kana: 'ちずを|みせて|ください',
      slot:null, formality:'polite',
      mcWrong: ['chizu o kudasai','doko desu ka','onegaishimasu'] },

    { id:'d10', theme:'directions',
      scenario: "You want to tell a taxi driver where you want to go",
      english: "I want to go to [place]",
      romaji: '[place] ni ikitai desu', kana: '[place]に|いきたい|です',
      slot:'place', slotScenario:'a destination',
      fallback:{ romaji:'eki', kana:'えき', english:'the station' },
      formality:'polite',
      mcWrong: ['[place] ni imasu','[place] kara kimashita','[place] wa doko desu ka'] },

    // ══ HOTEL & ACCOMMODATION ══════════════════════════════
    { id:'h1', theme:'hotel',
      scenario: "You arrive at the hotel reception and tell them you booked in advance",
      english: "I have a reservation",
      romaji: 'yoyaku ga arimasu', kana: 'よやくが|あります',
      slot:null, formality:'polite',
      mcWrong: ['yoyaku o shitai desu','heya ga arimasu ka','chekkuin onegaishimasu'] },

    { id:'h2', theme:'hotel',
      scenario: "You arrive and want to check in to your room",
      english: "check-in, please",
      romaji: 'chekkuin onegaishimasu', kana: 'チェックイン|おねがいします',
      slot:null, formality:'polite',
      mcWrong: ['chekku auto onegaishimasu','yoyaku ga arimasu','heya no kagi desu'] },

    { id:'h3', theme:'hotel',
      scenario: "You're leaving the hotel and need to check out",
      english: "check-out, please",
      romaji: 'chekku auto onegaishimasu', kana: 'チェックアウト|おねがいします',
      slot:null, formality:'polite',
      mcWrong: ['chekkuin onegaishimasu','yoyaku ga arimasu','mou ippaku shitai desu'] },

    { id:'h4', theme:'hotel',
      scenario: "The receptionist hands you something and you confirm it's your room key",
      english: "the room key",
      romaji: 'heya no kagi desu', kana: 'へやの|かぎ|です',
      slot:null, formality:'polite',
      mcWrong: ['heya wa doko desu ka','kagi o kudasai','chekkuin onegaishimasu'] },

    { id:'h5', theme:'hotel',
      scenario: "You want to connect to wi-fi and need the password",
      english: "what's the wi-fi password?",
      romaji: 'wai-fai no pasuwaado wa nan desu ka', kana: 'Wi-Fiの|パスワードは|なんですか',
      slot:null, formality:'polite',
      mcWrong: ['wai-fai ga arimasu ka','intaanetto wa doko desu ka','pasuwaado o kudasai'] },

    { id:'h6', theme:'hotel',
      scenario: "You want to know when breakfast is served",
      english: "what time is breakfast?",
      romaji: 'asagohan wa nanji desu ka', kana: 'あさごはんは|なんじ|ですか',
      slot:null, formality:'polite',
      mcWrong: ['asagohan wa oishii desu ka','asagohan o kudasai','nanji ni okimasu ka'] },

    { id:'h7', theme:'hotel',
      scenario: "You're enjoying your stay and want to extend by one night",
      english: "I want to stay one more night",
      romaji: 'mou ippaku shitai desu', kana: 'もう|いっぱく|したい|です',
      slot:null, formality:'polite',
      mcWrong: ['chekku auto onegaishimasu','yoyaku ga arimasu','heya ga hoshii desu'] },

    { id:'h8', theme:'hotel',
      scenario: "You're at a ryokan and want to find the communal bath",
      english: "where is the [room]?",
      romaji: '[room] wa doko desu ka', kana: '[room]は|どこ|ですか',
      slot:'room', slotScenario:'a room or facility',
      fallback:{ romaji:'ofuro', kana:'おふろ', english:'the bath' },
      formality:'polite',
      mcWrong: ['[room] o kudasai','[room] ga arimasu ka','[room] ni ikimasu'] },

    // ══ HELP & EMERGENCIES ════════════════════════════════
    { id:'e1', theme:'help',
      scenario: "You're in danger and need someone to come to your aid",
      english: "please help me!",
      romaji: 'tasukete kudasai', kana: 'たすけて|ください',
      slot:null, formality:'polite',
      mcWrong: ['sumimasen','daijoubu desu ka','keisatsu o yonde kudasai'] },

    { id:'e2', theme:'help',
      scenario: "There's an immediate emergency and you need help right now",
      english: "help!",
      romaji: 'tasukete', kana: 'たすけて',
      slot:null, formality:'casual',
      notes: 'The urgent version — shout if needed',
      mcWrong: ['sumimasen','abunai','ittekimasu'] },

    { id:'e3', theme:'help',
      scenario: "You're feeling very unwell and need to explain this to someone",
      english: "I am sick",
      romaji: 'byouki desu', kana: 'びょうき|です',
      slot:null, formality:'polite',
      mcWrong: ['tsukaremashita','daijoubu desu','itai desu'] },

    { id:'e4', theme:'help',
      scenario: "You need to tell someone which part of your body is hurting",
      english: "my [body part] hurts",
      romaji: '[body-part] ga itai desu', kana: '[body-part]が|いたい|です',
      slot:'body-part', slotScenario:'a body part',
      fallback:{ romaji:'atama', kana:'あたま', english:'head' },
      formality:'polite',
      mcWrong: ['[body-part] ga arimasu','[body-part] wa doko desu ka','[body-part] desu'] },

    { id:'e5', theme:'help',
      scenario: "Someone is seriously ill and you need a doctor urgently",
      english: "please call a doctor",
      romaji: 'isha o yonde kudasai', kana: 'いしゃを|よんで|ください',
      slot:null, formality:'polite',
      mcWrong: ['kyuukyuusha o yonde kudasai','keisatsu o yonde kudasai','tasukete kudasai'] },

    { id:'e6', theme:'help',
      scenario: "There's a crime in progress and you need the police",
      english: "please call the police",
      romaji: 'keisatsu o yonde kudasai', kana: 'けいさつを|よんで|ください',
      slot:null, formality:'polite',
      mcWrong: ['isha o yonde kudasai','kyuukyuusha o yonde kudasai','tasukete'] },

    { id:'e7', theme:'help',
      scenario: "Someone is seriously hurt and needs an ambulance immediately",
      english: "please call an ambulance",
      romaji: 'kyuukyuusha o yonde kudasai', kana: 'きゅうきゅうしゃを|よんで|ください',
      slot:null, formality:'polite',
      mcWrong: ['isha o yonde kudasai','keisatsu o yonde kudasai','tasukete kudasai'] },

    { id:'e8', theme:'help',
      scenario: "You arrive at the airport and can't find your bag on the carousel",
      english: "I lost my luggage",
      romaji: 'nimotsu o nakushimashita', kana: 'にもつを|なくしました',
      slot:null, formality:'polite',
      mcWrong: ['nimotsu ga arimasu','nimotsu wa doko desu ka','nimotsu o kudasai'] },

    { id:'e9', theme:'help',
      scenario: "You've been wandering for an hour and have no idea where you are",
      english: "I'm lost",
      romaji: 'michi ni mayoimashita', kana: 'みちに|まよいました',
      slot:null, formality:'polite',
      mcWrong: ['doko desu ka','chizu o misete kudasai','michi wa doko desu ka'] },

    { id:'e10', theme:'help',
      scenario: "You see someone fall over and want to check if they're okay",
      english: "are you okay?",
      romaji: 'daijoubu desu ka', kana: 'だいじょうぶ|ですか',
      slot:null, formality:'polite',
      mcWrong: ['genki desu ka','itai desu ka','byouki desu ka'] },

    { id:'e11', theme:'help',
      scenario: "Someone asks if you're alright after a small accident",
      english: "I'm okay",
      romaji: 'daijoubu desu', kana: 'だいじょうぶ|です',
      slot:null, formality:'polite',
      mcWrong: ['byouki desu','genki desu','itai desu'] },

    // ══ NUMBERS & MONEY ═══════════════════════════════════
    { id:'n1', theme:'numbers',
      scenario: "The market vendor tells you an item costs 100 yen",
      english: "it's 100 yen",
      romaji: 'hyaku-en desu', kana: 'ひゃくえん|です',
      slot:null, formality:'polite',
      mcWrong: ['sen-en desu','hyaku desu','en ga arimasu'] },

    { id:'n2', theme:'numbers',
      scenario: "The cashier shows you the total is 1,000 yen",
      english: "it's 1,000 yen",
      romaji: 'sen-en desu', kana: 'せんえん|です',
      slot:null, formality:'polite',
      mcWrong: ['hyaku-en desu','ichiman-en desu','ikura desu ka'] },

    { id:'n3', theme:'numbers',
      scenario: "The machine is broken and you want to pay with cash",
      english: "I'll pay in cash",
      romaji: 'genkin de haraimasu', kana: 'げんきんで|はらいます',
      slot:null, formality:'polite',
      mcWrong: ['kaado de haraemasu ka','ikura desu ka','otsuri o kudasai'] },

    { id:'n4', theme:'numbers',
      scenario: "You don't have cash and need to check if card payment is accepted",
      english: "can I pay by card?",
      romaji: 'kaado de haraemasu ka', kana: 'カードで|はらえますか',
      slot:null, formality:'polite',
      mcWrong: ['genkin de haraimasu','ikura desu ka','kurejitto kaado wa arimasu ka'] },

    { id:'n5', theme:'numbers',
      scenario: "You're buying multiple items and want to know the total",
      english: "how much in total?",
      romaji: 'zenbu de ikura desu ka', kana: 'ぜんぶで|いくら|ですか',
      slot:null, formality:'polite',
      mcWrong: ['ikura desu ka','zenbu o kudasai','otsuri wa ikura desu ka'] },

    { id:'n6', theme:'numbers',
      scenario: "You want to order a specific quantity of something",
      english: "[number] please",
      romaji: '[number-word] kudasai', kana: '[number-word]|ください',
      slot:'number-word', slotScenario:'a quantity',
      fallback:{ romaji:'futatsu', kana:'ふたつ', english:'two' },
      formality:'polite',
      mcWrong: ['[number-word] ga arimasu ka','[number-word] desu','[number-word] ikura desu ka'] },

    { id:'n7', theme:'numbers',
      scenario: "You've paid and the cashier gives you too much change",
      english: "how much change?",
      romaji: 'otsuri wa ikura desu ka', kana: 'おつりは|いくら|ですか',
      slot:null, formality:'polite',
      mcWrong: ['ikura desu ka','zenbu de ikura desu ka','otsuri o kudasai'] },

    { id:'n8', theme:'numbers',
      scenario: "You paid and want a receipt for your records",
      english: "receipt, please",
      romaji: 'reshiito o kudasai', kana: 'レシートを|ください',
      slot:null, formality:'polite',
      mcWrong: ['menyuu o kudasai','okaikei onegaishimasu','kore o kudasai'] },

    // ══ SMALL TALK ════════════════════════════════════════
    { id:'t1', theme:'smalltalk',
      scenario: "You run into someone you know and want to ask how they are",
      english: "how are you?",
      romaji: 'genki desu ka', kana: 'げんき|ですか',
      slot:null, formality:'polite',
      mcWrong: ['onamae wa nan desu ka','daijoubu desu ka','ii tenki desu ne'] },

    { id:'t2', theme:'smalltalk',
      scenario: "Someone asks how you are and you're feeling great",
      english: "I'm good",
      romaji: 'genki desu', kana: 'げんき|です',
      slot:null, formality:'polite',
      mcWrong: ['tsukaremashita','byouki desu','daijoubu desu'] },

    { id:'t3', theme:'smalltalk',
      scenario: "You want to make light conversation about the nice weather",
      english: "nice weather isn't it?",
      romaji: 'ii tenki desu ne', kana: 'いい|てんき|ですね',
      slot:null, formality:'polite',
      notes: 'The ね softens and invites agreement',
      mcWrong: ['atsui desu ne','samui desu ne','ame desu ne'] },

    { id:'t4', theme:'smalltalk',
      scenario: "You want to comment on the current weather conditions",
      english: "it's [weather condition]",
      romaji: '[weather] desu ne', kana: '[weather]|ですね',
      slot:'weather', slotScenario:'a weather condition',
      fallback:{ romaji:'ame', kana:'あめ', english:'rainy' },
      formality:'polite',
      mcWrong: ['[weather] desu ka','[weather] ga suki desu','[weather] ja nai desu'] },

    { id:'t5', theme:'smalltalk',
      scenario: "It's a freezing day in winter and you want to say so",
      english: "it's cold",
      romaji: 'samui desu ne', kana: 'さむい|ですね',
      slot:null, formality:'polite',
      mcWrong: ['atsui desu ne','ii tenki desu ne','suzushii desu ne'] },

    { id:'t6', theme:'smalltalk',
      scenario: "It's the middle of summer and the heat is intense",
      english: "it's hot",
      romaji: 'atsui desu ne', kana: 'あつい|ですね',
      slot:null, formality:'polite',
      mcWrong: ['samui desu ne','ii tenki desu ne','atatakai desu ne'] },

    { id:'t7', theme:'smalltalk',
      scenario: "Someone asks what you think of Japan and you want to compliment it",
      english: "Japan is wonderful",
      romaji: 'nihon wa subarashii desu', kana: 'にほんは|すばらしい|です',
      slot:null, formality:'polite',
      mcWrong: ['nihon ga suki desu','nihon wa ookii desu','nihon wa tanoshii desu'] },

    { id:'t8', theme:'smalltalk',
      scenario: "You're at a festival and want to say how enjoyable it is",
      english: "it's fun!",
      romaji: 'tanoshii desu', kana: 'たのしい|です',
      slot:null, formality:'polite',
      mcWrong: ['omoshiroi desu','subarashii desu','kawaii desu'] },

    { id:'t9', theme:'smalltalk',
      scenario: "After a long day of sightseeing you want to express how tired you are",
      english: "I'm tired",
      romaji: 'tsukaremashita', kana: 'つかれました',
      slot:null, formality:'polite',
      mcWrong: ['nemui desu','byouki desu','genki desu'] },

    { id:'t10', theme:'smalltalk',
      scenario: "It's been hours since you ate and you want to mention you're hungry",
      english: "I'm hungry",
      romaji: 'onaka ga sukimashita', kana: 'おなかが|すきました',
      slot:null, formality:'polite',
      mcWrong: ['tsukaremashita','nodo ga kawaita','tabetai desu'] },

    { id:'t11', theme:'smalltalk',
      scenario: "Someone offers you food and you want to say you like that dish",
      english: "I like [food]",
      romaji: '[food] ga suki desu', kana: '[food]が|すき|です',
      slot:'food', slotScenario:'a food',
      fallback:{ romaji:'sushi', kana:'すし', english:'sushi' },
      formality:'polite',
      mcWrong: ['[food] ga kirai desu','[food] o tabemasu','[food] ga oishii desu'] },

    { id:'t12', theme:'smalltalk',
      scenario: "Someone asks about your favourite colour",
      english: "my favourite colour is [colour]",
      romaji: 'sukina iro wa [colour] desu', kana: 'すきな|いろは|[colour]|です',
      slot:'colour', slotScenario:'a colour',
      fallback:{ romaji:'ao', kana:'あお', english:'blue' },
      formality:'polite',
      mcWrong: ['[colour] ga arimasu','[colour] desu ka','[colour] o kudasai'] },
  ],
};
